# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'week1-flix' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for week1-flix
pod "AlamofireImage"

  target 'week1-flixTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'week1-flixUITests' do
    # Pods for testing
  end

end
